package com.guttv.mapper;

import java.util.Set;

import com.guttv.model.DataAuth;

public interface DataAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_auth
     *
     * @mbg.generated
     */
    int insert(DataAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_auth
     *
     * @mbg.generated
     */
    int insertSelective(DataAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_auth
     *
     * @mbg.generated
     */
    DataAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataAuth record);

	/**   
	 * @Description: TODO
	 * @author: koukaiqiang   
	 * @version: 1.1
	 * @date:   2017年6月21日 下午3:16:14
	 *
	 * @param id
	 * @return  
	 */  
	Set<Integer> findRoleIdById(Integer id);

	/**   
	 * @Description: TODO
	 * @author: koukaiqiang   
	 * @version: 1.1
	 * @date:   2017年6月21日 下午3:21:58
	 *
	 * @param id
	 * @return  
	 */  
	DataAuth findBySelectId(String id);
}