package com.guttv.mapper;

import com.guttv.model.DataRole;

public interface DataRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_role
     *
     * @mbg.generated
     */
    int insert(DataRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_role
     *
     * @mbg.generated
     */
    int insertSelective(DataRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_role
     *
     * @mbg.generated
     */
    DataRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_data_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataRole record);
}