package com.guttv.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.guttv.model.ServiceGroup;
import com.guttv.vo.PageVO;

public interface ServiceGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_servicegroup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_servicegroup
     *
     * @mbg.generated
     */
    int insert(ServiceGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_servicegroup
     *
     * @mbg.generated
     */
    int insertSelective(ServiceGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_servicegroup
     *
     * @mbg.generated
     */
    ServiceGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_servicegroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ServiceGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_servicegroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ServiceGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_servicegroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServiceGroup record);

	/**   
	 * @Description: TODO
	 * @author: koukaiqiang   
	 * @version: 1.1
	 * @date:   2017年6月21日 下午2:45:31
	 *
	 * @param pageVO
	 * @return  
	 */  
	List<ServiceGroup> findPage(@Param("pageVO") PageVO pageVO);

	/**   
	 * @Description: TODO
	 * @author: koukaiqiang   
	 * @version: 1.1
	 * @date:   2017年6月21日 下午2:45:35
	 *
	 * @param serviceType
	 * @param pageVO
	 * @return  
	 */  
	List<ServiceGroup> findPageByStatus(@Param("status") int status, @Param("pageVO") PageVO pageVO);
}