package com.guttv.mapper;

import java.util.Set;

import com.guttv.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

	/**   
	 * @Description: TODO
	 * @author: koukaiqiang   
	 * @version: 1.1
	 * @date:   2017年6月21日 下午2:17:11
	 *
	 * @param userName
	 * @return  
	 */  
	User findByUserName(String userName);

	/**   
	 * @Description: TODO
	 * @author: koukaiqiang   
	 * @version: 1.1
	 * @date:   2017年6月21日 下午2:17:15
	 *
	 * @param id
	 * @return  
	 */  
	Set<String> findAuthsById(Integer id);

	/**   
	 * @Description: TODO
	 * @author: koukaiqiang   
	 * @version: 1.1
	 * @date:   2017年6月21日 下午2:57:18
	 *
	 * @param id
	 * @return  
	 */  
	Set<Integer> findRolesById(Integer id);
}