package com.guttv.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table b_data_auth
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DataAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_data_auth.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_data_auth.authName
     *
     * @mbg.generated
     */
    private String authName;

    /**
     * Database Column Remarks:
     *   对应查询总数的sql的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_data_auth.selectCountId
     *
     * @mbg.generated
     */
    private String selectCountId;

    /**
     * Database Column Remarks:
     *   对应查询sql的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_data_auth.selectListId
     *
     * @mbg.generated
     */
    private String selectListId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_data_auth.removeField
     *
     * @mbg.generated
     */
    private String removeField;

    /**
     * Database Column Remarks:
     *   对应sql字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_data_auth.fieldName
     *
     * @mbg.generated
     */
    private String fieldName;

    /**
     * Database Column Remarks:
     *   对应sql字段值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_data_auth.fieldValue
     *
     * @mbg.generated
     */
    private String fieldValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_data_auth.id
     *
     * @return the value of b_data_auth.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_data_auth.id
     *
     * @param id the value for b_data_auth.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_data_auth.authName
     *
     * @return the value of b_data_auth.authName
     *
     * @mbg.generated
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_data_auth.authName
     *
     * @param authName the value for b_data_auth.authName
     *
     * @mbg.generated
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_data_auth.selectCountId
     *
     * @return the value of b_data_auth.selectCountId
     *
     * @mbg.generated
     */
    public String getSelectCountId() {
        return selectCountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_data_auth.selectCountId
     *
     * @param selectCountId the value for b_data_auth.selectCountId
     *
     * @mbg.generated
     */
    public void setSelectCountId(String selectCountId) {
        this.selectCountId = selectCountId == null ? null : selectCountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_data_auth.selectListId
     *
     * @return the value of b_data_auth.selectListId
     *
     * @mbg.generated
     */
    public String getSelectListId() {
        return selectListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_data_auth.selectListId
     *
     * @param selectListId the value for b_data_auth.selectListId
     *
     * @mbg.generated
     */
    public void setSelectListId(String selectListId) {
        this.selectListId = selectListId == null ? null : selectListId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_data_auth.removeField
     *
     * @return the value of b_data_auth.removeField
     *
     * @mbg.generated
     */
    public String getRemoveField() {
        return removeField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_data_auth.removeField
     *
     * @param removeField the value for b_data_auth.removeField
     *
     * @mbg.generated
     */
    public void setRemoveField(String removeField) {
        this.removeField = removeField == null ? null : removeField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_data_auth.fieldName
     *
     * @return the value of b_data_auth.fieldName
     *
     * @mbg.generated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_data_auth.fieldName
     *
     * @param fieldName the value for b_data_auth.fieldName
     *
     * @mbg.generated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_data_auth.fieldValue
     *
     * @return the value of b_data_auth.fieldValue
     *
     * @mbg.generated
     */
    public String getFieldValue() {
        return fieldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_data_auth.fieldValue
     *
     * @param fieldValue the value for b_data_auth.fieldValue
     *
     * @mbg.generated
     */
    public void setFieldValue(String fieldValue) {
        this.fieldValue = fieldValue == null ? null : fieldValue.trim();
    }
}