package com.guttv.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_servicegroup
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ServiceGroup {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   业务分组名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   业务分组唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   渠道商唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.agentvendorcode
     *
     * @mbg.generated
     */
    private String agentvendorcode;

    /**
     * Database Column Remarks:
     *   图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.pictureurl1
     *
     * @mbg.generated
     */
    private String pictureurl1;

    /**
     * Database Column Remarks:
     *   状态 0:无,1:启用,2:停用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   是否已删除,TRUE:1 FALSE:0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.isdelete
     *
     * @mbg.generated
     */
    private Boolean isdelete;

    /**
     * Database Column Remarks:
     *   绑定的导航code,现在在业务组合中绑定导航信息，该字段废弃
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.navigationcode
     *
     * @mbg.generated
     */
    private String navigationcode;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_servicegroup.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.id
     *
     * @return the value of t_servicegroup.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.id
     *
     * @param id the value for t_servicegroup.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.name
     *
     * @return the value of t_servicegroup.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.name
     *
     * @param name the value for t_servicegroup.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.code
     *
     * @return the value of t_servicegroup.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.code
     *
     * @param code the value for t_servicegroup.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.agentvendorcode
     *
     * @return the value of t_servicegroup.agentvendorcode
     *
     * @mbg.generated
     */
    public String getAgentvendorcode() {
        return agentvendorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.agentvendorcode
     *
     * @param agentvendorcode the value for t_servicegroup.agentvendorcode
     *
     * @mbg.generated
     */
    public void setAgentvendorcode(String agentvendorcode) {
        this.agentvendorcode = agentvendorcode == null ? null : agentvendorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.pictureurl1
     *
     * @return the value of t_servicegroup.pictureurl1
     *
     * @mbg.generated
     */
    public String getPictureurl1() {
        return pictureurl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.pictureurl1
     *
     * @param pictureurl1 the value for t_servicegroup.pictureurl1
     *
     * @mbg.generated
     */
    public void setPictureurl1(String pictureurl1) {
        this.pictureurl1 = pictureurl1 == null ? null : pictureurl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.status
     *
     * @return the value of t_servicegroup.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.status
     *
     * @param status the value for t_servicegroup.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.isdelete
     *
     * @return the value of t_servicegroup.isdelete
     *
     * @mbg.generated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.isdelete
     *
     * @param isdelete the value for t_servicegroup.isdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.navigationcode
     *
     * @return the value of t_servicegroup.navigationcode
     *
     * @mbg.generated
     */
    public String getNavigationcode() {
        return navigationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.navigationcode
     *
     * @param navigationcode the value for t_servicegroup.navigationcode
     *
     * @mbg.generated
     */
    public void setNavigationcode(String navigationcode) {
        this.navigationcode = navigationcode == null ? null : navigationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.createtime
     *
     * @return the value of t_servicegroup.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.createtime
     *
     * @param createtime the value for t_servicegroup.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.updatetime
     *
     * @return the value of t_servicegroup.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.updatetime
     *
     * @param updatetime the value for t_servicegroup.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_servicegroup.description
     *
     * @return the value of t_servicegroup.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_servicegroup.description
     *
     * @param description the value for t_servicegroup.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}